import { useState, useEffect } from 'react';
import { Send, Trash2, ExternalLink, ChevronUp, AlertCircle, CheckCircle, X, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Internal Alert Component
const Alert = ({ children, variant = 'default', onClose }) => {
  const styles = {
    default: 'bg-blue-50 text-blue-700 border-blue-200',
    success: 'bg-green-50 text-green-700 border-green-200',
    error: 'bg-red-50 text-red-700 border-red-200'
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      onClose();
    }, 5000);
    return () => clearTimeout(timer);
  }, [onClose]);

  return (
    <div className={`flex items-center justify-between p-4 rounded-lg border ${styles[variant]} mb-2`}>
      <div className="flex items-center">
        {variant === 'success' && <CheckCircle className="h-5 w-5 mr-2" />}
        {variant === 'error' && <AlertCircle className="h-5 w-5 mr-2" />}
        <div className="ml-1">{children}</div>
      </div>
      <button
        onClick={onClose}
        className="p-1 rounded-full hover:bg-gray-200 text-gray-500 hover:text-gray-700 transition-colors"
        title="Close"
      >
        <X className="h-4 w-4" />
      </button>
    </div>
  );
};

const ArticleSummaryPage = () => {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [articles, setArticles] = useState([]);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState('');
  const [isInputExpanded, setIsInputExpanded] = useState(false);

  useEffect(() => {
    fetchArticles();
  }, []);

  const fetchArticles = async () => {
    try {
      const response = await fetch('http://127.0.0.1:8000/articles');
      if (!response.ok) throw new Error('Failed to fetch articles');
      const data = await response.json();
      setArticles(data.reverse());
    } catch (err) {
      setError('Failed to load articles');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess('');
    
    try {
      const response = await fetch('http://127.0.0.1:8000/articles', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url }),
      });
      
      if (!response.ok) throw new Error('Failed to fetch summary');
      
      const data = await response.json();
      setArticles(prev => [data, ...prev]);
      setUrl('');
      setIsInputExpanded(false);
      setSuccess('Article successfully summarized!');
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (articleUrl) => {
    try {
      const response = await fetch(`http://127.0.0.1:8000/articles?url=${encodeURIComponent(articleUrl)}`, {
        method: 'DELETE',
        });
      
      if (!response.ok) throw new Error('Failed to delete article');
      await fetchArticles(); // Reload the articles
      setSuccess('Article successfully deleted!');
    } catch (err) {
      setError('Failed to delete article');
    }
  };

  const handleDownload = async (article) => {
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 72; // 1 inch margins in points
      const contentWidth = pageWidth - 2 * margin;
      let yPosition = margin;

      // Function to add header
      const addHeader = () => {
        doc.setFont('times', 'bold');
        doc.setFontSize(18);
        doc.text('Article Summary', margin, margin - 20);
        doc.setFont('times', 'normal');
        doc.setFontSize(10);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth - margin - 100, margin - 20);
        doc.setLineWidth(0.5);
        doc.line(margin, margin - 10, pageWidth - margin, margin - 10);
      };

      // Function to add footer
      const addFooter = (pageNumber) => {
        doc.setFont('times', 'normal');
        doc.setFontSize(10);
        doc.text(`Generated by News Summarizer`, margin, pageHeight - margin + 20);
        doc.text(`Page ${pageNumber}`, pageWidth - margin - 30, pageHeight - margin + 20);
        doc.setLineWidth(0.5);
        doc.line(margin, pageHeight - margin + 10, pageWidth - margin, pageHeight - margin + 10);
      };

      // Function to add watermark
      const addWatermark = () => {
        doc.setFont('times', 'italic');
        doc.setFontSize(40);
        doc.setTextColor(200, 200, 200); // Light gray for watermark
        doc.text('News Summarizer', pageWidth / 2, pageHeight / 2, { angle: 45, align: 'center' });
        doc.setTextColor(0, 0, 0); // Reset to black
      };

      // Add header, footer, and watermark to first page
      addHeader();
      addFooter(1);
      addWatermark();

      // Add original URL
      doc.setFont('times', 'normal');
      doc.setFontSize(12);
      const urlLines = doc.splitTextToSize(`Original Article URL: ${article.url}`, contentWidth);
      urlLines.forEach(line => {
        doc.text(line, margin, yPosition);
        yPosition += 18;
      });
      yPosition += 12;

      // Add image if available
      if (article.image) {
        try {
          const img = new Image();
          img.crossOrigin = 'Anonymous';
          img.src = article.image;
          await new Promise((resolve, reject) => {
            img.onload = () => resolve(img);
            img.onerror = () => reject(new Error('Failed to load image'));
          });
          const canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0);
          const imgData = canvas.toDataURL('image/jpeg');
          const imgProps = doc.getImageProperties(imgData);
          const maxImgWidth = contentWidth;
          const imgWidth = Math.min(imgProps.width, maxImgWidth);
          const imgHeight = (imgWidth / imgProps.width) * imgProps.height;
          
          // Check if image fits on current page
          if (yPosition + imgHeight > pageHeight - margin - 30) {
            doc.addPage();
            yPosition = margin;
            addHeader();
            addFooter(doc.internal.getNumberOfPages());
            addWatermark();
          }
          
          doc.addImage(imgData, 'JPEG', margin, yPosition, imgWidth, imgHeight);
          yPosition += imgHeight + 18;
        } catch (err) {
          console.error('Image loading error:', err);
          doc.setFont('times', 'italic');
          doc.setFontSize(12);
          doc.text('Image not available', margin, yPosition);
          yPosition += 18;
          doc.setFont('times', 'normal');
        }
      }

      // Add summary
      const lines = article.summary.split('\n');
      lines.forEach(line => {
        if (yPosition > pageHeight - margin - 30) {
          doc.addPage();
          yPosition = margin;
          addHeader();
          addFooter(doc.internal.getNumberOfPages());
          addWatermark();
        }

        if (line.trim().startsWith('**')) {
          const heading = line.trim().replace(/^\*\*|\*\*$/g, '');
          doc.setFont('times', 'bold');
          doc.setFontSize(16);
          const headingLines = doc.splitTextToSize(heading, contentWidth);
          headingLines.forEach(hLine => {
            doc.text(hLine, margin, yPosition);
            yPosition += 20;
          });
          doc.setFont('times', 'normal');
          doc.setFontSize(12);
        } else if (line.trim().startsWith('* ')) {
          const bulletText = line.trim().substring(2);
          const bulletLines = doc.splitTextToSize(bulletText, contentWidth - 10);
          doc.text('•', margin, yPosition);
          bulletLines.forEach(bLine => {
            doc.text(bLine, margin + 10, yPosition);
            yPosition += 18;
          });
        } else if (line.trim()) {
          const textLines = doc.splitTextToSize(line.trim(), contentWidth);
          textLines.forEach(tLine => {
            doc.text(tLine, margin, yPosition);
            yPosition += 18;
          });
        }
      });

      // Save the PDF
      const fileName = `${article.url.split('/').pop() || 'article'}_summary.pdf`;
      doc.save(fileName);
    } catch (err) {
      setError('Failed to generate PDF');
      console.error('PDF generation error:', err);
    }
  };

  const formatText = (text) => {
    const lines = text.split('\n');
    const formattedContent = [];
    let currentSection = null;
    
    lines.forEach(line => {
      if (line.trim().startsWith('**')) {
        if (currentSection) formattedContent.push(currentSection);
        const headingText = line.trim().replace(/^\*\*|\*\*$/g, '');
        currentSection = { heading: headingText, content: [] };
      } else if (line.trim().startsWith('* ')) {
        if (currentSection) {
          currentSection.content.push({
            type: 'bullet',
            text: line.trim().substring(2)
          });
        }
      } else if (line.trim()) {
        if (currentSection) {
          currentSection.content.push({
            type: 'text',
            text: line.trim()
          });
        }
      }
    });
    
    if (currentSection) formattedContent.push(currentSection);
    
    return formattedContent.map((section, idx) => (
      <div key={idx} className="mb-6">
        <h2 className="text-xl font-bold text-gray-800 mb-3">
          {section.heading}
        </h2>
        <div className="space-y-3">
          {section.content.map((item, contentIdx) => {
            if (item.type === 'bullet') {
              return (
                <ul key={contentIdx} className="list-disc pl-6">
                  <li className="text-gray-700">{item.text}</li>
                </ul>
              );
            }
            return (
              <p key={contentIdx} className="text-gray-700 leading-relaxed">
                {item.text}
              </p>
            );
          })}
        </div>
      </div>
    ));
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-24">
      {/* Header */}
      <div className="backdrop-blur-md bg-transparent xl:max-w-max sticky top-0 z-10">
        <div className="px-2 py-4">
          <h1 className="text-md md:text-xl font-bold text-zinc-800">Article Summarizer</h1>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-5xl mx-auto px-4 py-6">
        {/* Notifications */}
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 w-full max-w-md z-50">
          {error && (
            <Alert variant="error" onClose={() => setError(null)}>
              {error}
            </Alert>
          )}
          {success && (
            <Alert variant="success" onClose={() => setSuccess('')}>
              {success}
            </Alert>
          )}
        </div>

        {/* Articles Grid */}
        <div className="grid gap-6">
          {articles.map((article, idx) => (
            <div key={idx} className="bg-white rounded-xl shadow-sm overflow-hidden border border-gray-100 hover:shadow-md transition-shadow">
              {/* Image Section */}
              {article.image && (
                <div className="w-full h-48 md:h-64 relative">
                  <img
                    src={article.image}
                    alt="Article thumbnail"
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent" />
                </div>
              )}
              
              {/* Content Section */}
              <div className="p-6">
                <div className="flex justify-between items-start mb-4">
                  <h2 className="text-lg font-semibold text-gray-900 flex-1 pr-4">
                    {article.url.split('/').pop() || 'Article Summary'}
                  </h2>
                  <div className="flex gap-3">
                    <button
                      onClick={() => window.open(article.url, '_blank')}
                      className="p-2 rounded-full hover:bg-gray-100 text-gray-500 hover:text-blue-600 transition-colors hover:cursor-pointer"
                      title="Open original article"
                    >
                      <ExternalLink className="h-5 w-5" />
                    </button>
                    <button
                      onClick={() => handleDownload(article)}
                      className="p-2 rounded-full hover:bg-gray-100 text-gray-500 hover:text-green-600 transition-colors hover:cursor-pointer"
                      title="Download summary"
                    >
                      <Download className="h-5 w-5" />
                    </button>
                    <button
                      onClick={() => handleDelete(article.url)}
                      className="p-2 rounded-full hover:bg-gray-100 text-gray-500 hover:text-red-600 transition-colors hover:cursor-pointer"
                      title="Delete summary"
                    >
                      <Trash2 className="h-5 w-5" />
                    </button>
                  </div>
                </div>
                {formatText(article.summary)}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Fixed Input Section */}
      <div className={`fixed bottom-0 left-0 right-0 bg-white shadow-lg border-t border-gray-200 z-20`}>
        <div className="max-w-5xl mx-auto px-4">
          <div className={`transform transition-all duration-300 ${isInputExpanded ? 'py-8' : 'py-4'}`}>
            <button
              onClick={() => setIsInputExpanded(!isInputExpanded)}
              className="absolute -top-10 right-4 bg-white rounded-t-lg px-4 py-2 shadow-lg border border-gray-200 border-b-0 text-gray-600 hover:text-gray-900 hover:cursor-pointer transition-colors"
            >
              <ChevronUp className={`h-5 w-5 transform transition-transform ${isInputExpanded ? 'rotate-180' : ''}`} />
            </button>
            
            <form onSubmit={handleSubmit} className={`transition-all duration-300`}>
              <div className="flex gap-4">
                <input
                  type="url"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="Enter article URL to summarize..."
                  required
                  className="flex-1 px-4 py-2 rounded-lg border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                />
                <button
                  type="submit"
                  disabled={loading}
                  className="inline-flex items-center px-6 py-2 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 transition-colors hover:cursor-pointer"
                >
                  {loading ? (
                    'Processing...'
                  ) : (
                    <>
                      Summarize
                      <Send className="ml-2 h-4 w-4" />
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ArticleSummaryPage;